name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      TERM: dumb
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: |
            package-lock.json
            tests/webpack-tree-shaking/package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm run unit
      - run: npm run build
      - run: npm run integration
      - run: npm run website:build
      - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/dist
          cname: decimali.sh
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
      - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: JS-DevTools/npm-publish@v1
        with:
          package: ./dist/package.json
          token: ${{ secrets.NPM_TOKEN }}
